fulls1z3/angular-tslint-rules

README.md, package.json
** PR Type
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build: add standard version

.circleci/config.yml
** PR Type
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
=> ci: downgrade to yarn v0.x

.npmignore
** PR Type
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
=> refactor: update .npmignore

README.md, package.json, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(atr): update rules to tslint v5.8.0 & codelyzer v4.0.1

LICENSE, README.md, package.json, tslint.json, yarn.lock
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(atr): update rules to tslint v5.9.0 & codelyzer v4.1.0

README.md
** PR Type
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(readme): fix readme

README.md, tslint.json
** PR Type
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
=> fix: fix codelyzer rules

README.md, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(atr): remove `import-blacklist`

README.md, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(atr): update rules (tslint@5.10.0)

README.md, tslint.json
** PR Type
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(atr): fix rule `comment-format`

README.md, package.json, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(atr): update rules (tslint@5.11.0)

README.md, package.json, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(atr): update rules (codelyzer@4.4.2)

README.md, package.json, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(atr): update rules (tslint@5.12.0)

README.md, package.json, tslint.json, yarn.lock
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(atr): update tslint rules

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md, README.md, package.json
** PR Type
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(github): update docs

.circleci/config.yml, .editorconfig, CONTRIBUTING.md, commitlint.config.js, package.json, yarn.lock
** PR Type
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
=> build(npm): add semantic release

.npmignore
** PR Type
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(npm): update ignorefile

.npmignore, package.json, release-rules.js
** PR Type
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(npm): update config

README.md, tslint.json
** PR Type
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
=> refactor(core): add ignore patterns for  max-line-length

README.md, tslint.json
** PR Type
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(core): set max-file-line-count to 400

README.md, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): update rules tslint@5.15.0

README.md, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): update rules tslint@5.16

README.md
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): update rules tslint@5.17.0

README.md, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): update rules tslint@5.18.0

README.md, package.json, tslint.json
** PR Type
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): update rules tslint@5.20.0

package.json, tslint.json, yarn.lock
** PR Type
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(core): add EventEmitter to invalid-void rule exclusion
